version: "3.1"
services:

  backend:
    build: ./app-backend
    container_name: backend
    ports:
      -'8080:8080'
    volumes:
      -//app-backend:app

  frontend:
    build: ./app-frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./app-frontend:/app
      # - ./app/node_modules
    # stdin_open: true
    # tty: true